### PR TITLE
Added "T-Shirt and Numbers" option

### PR DESCRIPTION
**Pull request by moritzluedtke**

### CODE REVIEW

**Review by hellomuthu23 — COMMENTED** [review]
Looks good @moritzluedtke. This option can be certainly useful for few users. Just need to add unit tests and test it in preview env.

**Comment by moritzluedtke** [comment]
Thanks for taking a look. I'll try to fix them soon.

**Comment by moritzluedtke** [comment]
@hellomuthu23 I added some tests (should've done that in the first place, sorry) and fixed the broken one.

**Comment by moritzluedtke** [comment]
I'd need some support with the failing workflow since I have no experience with your setup and Firebase. Looks like a config problem, though.

**Review by hellomuthu23 — APPROVED** [review]

**Comment by hellomuthu23** [comment]
> I'd need some support with the failing workflow since I have no experience with your setup and Firebase. Looks like a config problem, though.

yes, its a config problem. When the branch is not from actual source and the user doesn't have access to secrets.

**Comment by moritzluedtke** [comment]
Ah, I see. Thanks for the explanation and the quick merging of my PR!

**Comment by hellomuthu23** [comment]
> Ah, I see. Thanks for the explanation and the quick merging of my PR!

no problem, thanks a lot for your contribution. Highly appreciated

**Pull request merged**
